// v2 统一线协议（WebSocket+Protobuf）：/ws/v2（浏览器）、/ws/v2/agent（桌面端）、
// /ws/v2/terminal（终端数据面）三链路的帧壳。一条 WS 二进制消息承载一条帧，文本帧即协议错误；
// 首帧必须为 hello，鉴权失败以 close code 4401 关闭。业务载荷复用 v1 消息（三端唯一事实源，
// 永不弃用、编号只增不改），本文件仅新增帧壳与未曾 proto 化的网关本地载荷。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v2/gateway_ws.proto

package gatewayv2

import (
	v1 "github.com/liveagent/agent-gateway/internal/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientRole 区分 /ws/v2/terminal 上连接的所属端（该链路两端共用一条路径，靠 hello.role 区分）。
type ClientRole int32

const (
	ClientRole_CLIENT_ROLE_UNSPECIFIED ClientRole = 0
	ClientRole_CLIENT_ROLE_BROWSER     ClientRole = 1
	ClientRole_CLIENT_ROLE_AGENT       ClientRole = 2
)

// Enum value maps for ClientRole.
var (
	ClientRole_name = map[int32]string{
		0: "CLIENT_ROLE_UNSPECIFIED",
		1: "CLIENT_ROLE_BROWSER",
		2: "CLIENT_ROLE_AGENT",
	}
	ClientRole_value = map[string]int32{
		"CLIENT_ROLE_UNSPECIFIED": 0,
		"CLIENT_ROLE_BROWSER":     1,
		"CLIENT_ROLE_AGENT":       2,
	}
)

func (x ClientRole) Enum() *ClientRole {
	p := new(ClientRole)
	*p = x
	return p
}

func (x ClientRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_v2_gateway_ws_proto_enumTypes[0].Descriptor()
}

func (ClientRole) Type() protoreflect.EnumType {
	return &file_proto_v2_gateway_ws_proto_enumTypes[0]
}

func (x ClientRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientRole.Descriptor instead.
func (ClientRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{0}
}

// ClientHello 是所有 v2 连接的第一帧。
type ClientHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 协议版本，当前恒为 2；未知版本被服务端拒绝。
	ProtocolVersion uint32     `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Role            ClientRole `protobuf:"varint,2,opt,name=role,proto3,enum=liveagent.gateway.v2.ClientRole" json:"role,omitempty"`
	// 网关访问令牌，服务端做常量时间比较。
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// 以下字段仅 CLIENT_ROLE_AGENT 使用（对应 v1 gRPC AuthRequest）。
	AgentId      string `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion string `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// 客户端标识（如 "webui" / "desktop"），仅用于观测与日志。
	ClientName    string `protobuf:"bytes,6,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientVersion string `protobuf:"bytes,7,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ClientHello) GetRole() ClientRole {
	if x != nil {
		return x.Role
	}
	return ClientRole_CLIENT_ROLE_UNSPECIFIED
}

func (x *ClientHello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ClientHello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ClientHello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *ClientHello) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *ClientHello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

// ServerHello 是服务端对 ClientHello 的应答；ok=false 时随即关闭连接。
type ServerHello struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Ok      bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 仅 agent 角色返回（对应 v1 gRPC AuthResponse.session_id）。
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 服务端 Unix 秒时间戳，供客户端校准。
	ServerTime int64 `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// 服务端心跳周期与消息大小上限，客户端应据此配置本地看门狗与分片。
	HeartbeatPeriodSeconds uint32 `protobuf:"varint,5,opt,name=heartbeat_period_seconds,json=heartbeatPeriodSeconds,proto3" json:"heartbeat_period_seconds,omitempty"`
	MaxMessageBytes        uint64 `protobuf:"varint,6,opt,name=max_message_bytes,json=maxMessageBytes,proto3" json:"max_message_bytes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{1}
}

func (x *ServerHello) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ServerHello) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerHello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ServerHello) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *ServerHello) GetHeartbeatPeriodSeconds() uint32 {
	if x != nil {
		return x.HeartbeatPeriodSeconds
	}
	return 0
}

func (x *ServerHello) GetMaxMessageBytes() uint64 {
	if x != nil {
		return x.MaxMessageBytes
	}
	return 0
}

// PingFrame / PongFrame 是应用层心跳：WS 控制帧 ping 探测网络栈，本帧探测页面 JS/事件循环存活。
type PingFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingFrame) Reset() {
	*x = PingFrame{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingFrame) ProtoMessage() {}

func (x *PingFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingFrame.ProtoReflect.Descriptor instead.
func (*PingFrame) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{2}
}

func (x *PingFrame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PongFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongFrame) Reset() {
	*x = PongFrame{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongFrame) ProtoMessage() {}

func (x *PongFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongFrame.ProtoReflect.Descriptor instead.
func (*PongFrame) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{3}
}

func (x *PongFrame) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// AckResult 是本地操作的通用确认应答（对应 v1 的 {"ok":true}）。
type AckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResult) Reset() {
	*x = AckResult{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResult) ProtoMessage() {}

func (x *AckResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResult.ProtoReflect.Descriptor instead.
func (*AckResult) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{4}
}

func (x *AckResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// WebClientFrame 为浏览器 → 网关方向的帧。除 agent_request 直通臂外，其余臂均为
// 网关本地操作（由网关自身状态应答，不经桌面端往返）。
type WebClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求关联 id，客户端生成、响应帧回携；广播事件与心跳帧为空。
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebClientFrame_Hello
	//	*WebClientFrame_AgentRequest
	//	*WebClientFrame_StatusGet
	//	*WebClientFrame_ChatCommand
	//	*WebClientFrame_ChatPrepare
	//	*WebClientFrame_ChatSubscribe
	//	*WebClientFrame_ChatUnsubscribe
	//	*WebClientFrame_ChatActivities
	//	*WebClientFrame_WorkspaceSubscribe
	//	*WebClientFrame_WorkspaceUnsubscribe
	//	*WebClientFrame_Pong
	Payload       isWebClientFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebClientFrame) Reset() {
	*x = WebClientFrame{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebClientFrame) ProtoMessage() {}

func (x *WebClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebClientFrame.ProtoReflect.Descriptor instead.
func (*WebClientFrame) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{5}
}

func (x *WebClientFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WebClientFrame) GetPayload() isWebClientFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebClientFrame) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WebClientFrame) GetAgentRequest() *v1.GatewayEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_AgentRequest); ok {
			return x.AgentRequest
		}
	}
	return nil
}

func (x *WebClientFrame) GetStatusGet() *StatusGetRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_StatusGet); ok {
			return x.StatusGet
		}
	}
	return nil
}

func (x *WebClientFrame) GetChatCommand() *v1.ChatCommandRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_ChatCommand); ok {
			return x.ChatCommand
		}
	}
	return nil
}

func (x *WebClientFrame) GetChatPrepare() *ChatPrepareRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_ChatPrepare); ok {
			return x.ChatPrepare
		}
	}
	return nil
}

func (x *WebClientFrame) GetChatSubscribe() *ChatSubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_ChatSubscribe); ok {
			return x.ChatSubscribe
		}
	}
	return nil
}

func (x *WebClientFrame) GetChatUnsubscribe() *ChatUnsubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_ChatUnsubscribe); ok {
			return x.ChatUnsubscribe
		}
	}
	return nil
}

func (x *WebClientFrame) GetChatActivities() *ChatActivitiesRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_ChatActivities); ok {
			return x.ChatActivities
		}
	}
	return nil
}

func (x *WebClientFrame) GetWorkspaceSubscribe() *WorkspaceSubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_WorkspaceSubscribe); ok {
			return x.WorkspaceSubscribe
		}
	}
	return nil
}

func (x *WebClientFrame) GetWorkspaceUnsubscribe() *WorkspaceUnsubscribeRequest {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_WorkspaceUnsubscribe); ok {
			return x.WorkspaceUnsubscribe
		}
	}
	return nil
}

func (x *WebClientFrame) GetPong() *PongFrame {
	if x != nil {
		if x, ok := x.Payload.(*WebClientFrame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isWebClientFrame_Payload interface {
	isWebClientFrame_Payload()
}

type WebClientFrame_Hello struct {
	Hello *ClientHello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type WebClientFrame_AgentRequest struct {
	// 直通请求：网关校验白名单与限额后转发桌面端（request_id 按连接命名空间化防冲突）。
	AgentRequest *v1.GatewayEnvelope `protobuf:"bytes,3,opt,name=agent_request,json=agentRequest,proto3,oneof"`
}

type WebClientFrame_StatusGet struct {
	StatusGet *StatusGetRequest `protobuf:"bytes,4,opt,name=status_get,json=statusGet,proto3,oneof"`
}

type WebClientFrame_ChatCommand struct {
	ChatCommand *v1.ChatCommandRequest `protobuf:"bytes,5,opt,name=chat_command,json=chatCommand,proto3,oneof"`
}

type WebClientFrame_ChatPrepare struct {
	ChatPrepare *ChatPrepareRequest `protobuf:"bytes,6,opt,name=chat_prepare,json=chatPrepare,proto3,oneof"`
}

type WebClientFrame_ChatSubscribe struct {
	ChatSubscribe *ChatSubscribeRequest `protobuf:"bytes,7,opt,name=chat_subscribe,json=chatSubscribe,proto3,oneof"`
}

type WebClientFrame_ChatUnsubscribe struct {
	ChatUnsubscribe *ChatUnsubscribeRequest `protobuf:"bytes,8,opt,name=chat_unsubscribe,json=chatUnsubscribe,proto3,oneof"`
}

type WebClientFrame_ChatActivities struct {
	ChatActivities *ChatActivitiesRequest `protobuf:"bytes,9,opt,name=chat_activities,json=chatActivities,proto3,oneof"`
}

type WebClientFrame_WorkspaceSubscribe struct {
	WorkspaceSubscribe *WorkspaceSubscribeRequest `protobuf:"bytes,10,opt,name=workspace_subscribe,json=workspaceSubscribe,proto3,oneof"`
}

type WebClientFrame_WorkspaceUnsubscribe struct {
	WorkspaceUnsubscribe *WorkspaceUnsubscribeRequest `protobuf:"bytes,11,opt,name=workspace_unsubscribe,json=workspaceUnsubscribe,proto3,oneof"`
}

type WebClientFrame_Pong struct {
	Pong *PongFrame `protobuf:"bytes,12,opt,name=pong,proto3,oneof"`
}

func (*WebClientFrame_Hello) isWebClientFrame_Payload() {}

func (*WebClientFrame_AgentRequest) isWebClientFrame_Payload() {}

func (*WebClientFrame_StatusGet) isWebClientFrame_Payload() {}

func (*WebClientFrame_ChatCommand) isWebClientFrame_Payload() {}

func (*WebClientFrame_ChatPrepare) isWebClientFrame_Payload() {}

func (*WebClientFrame_ChatSubscribe) isWebClientFrame_Payload() {}

func (*WebClientFrame_ChatUnsubscribe) isWebClientFrame_Payload() {}

func (*WebClientFrame_ChatActivities) isWebClientFrame_Payload() {}

func (*WebClientFrame_WorkspaceSubscribe) isWebClientFrame_Payload() {}

func (*WebClientFrame_WorkspaceUnsubscribe) isWebClientFrame_Payload() {}

func (*WebClientFrame_Pong) isWebClientFrame_Payload() {}

// WebServerFrame 为网关 → 浏览器方向的帧。
type WebServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 关联响应回填请求 id；服务端主动推送（广播/心跳）时为空。
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WebServerFrame_Hello
	//	*WebServerFrame_AgentResponse
	//	*WebServerFrame_LocalError
	//	*WebServerFrame_Ping
	//	*WebServerFrame_Status
	//	*WebServerFrame_ChatSubscribed
	//	*WebServerFrame_ChatAccepted
	//	*WebServerFrame_ChatActivities
	//	*WebServerFrame_ChatEvent
	//	*WebServerFrame_ChatCommandUpdate
	//	*WebServerFrame_ChatSubscriptionReset
	//	*WebServerFrame_ChatActivity
	//	*WebServerFrame_Ack
	//	*WebServerFrame_ChatCancelled
	//	*WebServerFrame_HistoryEvent
	//	*WebServerFrame_SettingsEvent
	//	*WebServerFrame_TerminalEvent
	//	*WebServerFrame_SftpEvent
	//	*WebServerFrame_ChatQueueEvent
	//	*WebServerFrame_TunnelState
	//	*WebServerFrame_ProcessState
	//	*WebServerFrame_WorkspaceActivity
	Payload       isWebServerFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebServerFrame) Reset() {
	*x = WebServerFrame{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebServerFrame) ProtoMessage() {}

func (x *WebServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebServerFrame.ProtoReflect.Descriptor instead.
func (*WebServerFrame) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{6}
}

func (x *WebServerFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WebServerFrame) GetPayload() isWebServerFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebServerFrame) GetHello() *ServerHello {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WebServerFrame) GetAgentResponse() *v1.AgentEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_AgentResponse); ok {
			return x.AgentResponse
		}
	}
	return nil
}

func (x *WebServerFrame) GetLocalError() *v1.ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_LocalError); ok {
			return x.LocalError
		}
	}
	return nil
}

func (x *WebServerFrame) GetPing() *PingFrame {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *WebServerFrame) GetStatus() *StatusEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *WebServerFrame) GetChatSubscribed() *ChatSubscribeResult {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_ChatSubscribed); ok {
			return x.ChatSubscribed
		}
	}
	return nil
}

func (x *WebServerFrame) GetChatAccepted() *ChatCommandAccepted {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_ChatAccepted); ok {
			return x.ChatAccepted
		}
	}
	return nil
}

func (x *WebServerFrame) GetChatActivities() *ChatActivitiesResult {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_ChatActivities); ok {
			return x.ChatActivities
		}
	}
	return nil
}

func (x *WebServerFrame) GetChatEvent() *ChatStreamEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_ChatEvent); ok {
			return x.ChatEvent
		}
	}
	return nil
}

func (x *WebServerFrame) GetChatCommandUpdate() *ChatCommandUpdate {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_ChatCommandUpdate); ok {
			return x.ChatCommandUpdate
		}
	}
	return nil
}

func (x *WebServerFrame) GetChatSubscriptionReset() *ChatSubscriptionReset {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_ChatSubscriptionReset); ok {
			return x.ChatSubscriptionReset
		}
	}
	return nil
}

func (x *WebServerFrame) GetChatActivity() *ChatActivityEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_ChatActivity); ok {
			return x.ChatActivity
		}
	}
	return nil
}

func (x *WebServerFrame) GetAck() *AckResult {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *WebServerFrame) GetChatCancelled() *ChatCancelResult {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_ChatCancelled); ok {
			return x.ChatCancelled
		}
	}
	return nil
}

func (x *WebServerFrame) GetHistoryEvent() *v1.HistorySyncEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_HistoryEvent); ok {
			return x.HistoryEvent
		}
	}
	return nil
}

func (x *WebServerFrame) GetSettingsEvent() *v1.SettingsSyncEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_SettingsEvent); ok {
			return x.SettingsEvent
		}
	}
	return nil
}

func (x *WebServerFrame) GetTerminalEvent() *v1.TerminalEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_TerminalEvent); ok {
			return x.TerminalEvent
		}
	}
	return nil
}

func (x *WebServerFrame) GetSftpEvent() *v1.SftpEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_SftpEvent); ok {
			return x.SftpEvent
		}
	}
	return nil
}

func (x *WebServerFrame) GetChatQueueEvent() *v1.ChatQueueEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_ChatQueueEvent); ok {
			return x.ChatQueueEvent
		}
	}
	return nil
}

func (x *WebServerFrame) GetTunnelState() *v1.TunnelStateSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_TunnelState); ok {
			return x.TunnelState
		}
	}
	return nil
}

func (x *WebServerFrame) GetProcessState() *v1.ManagedProcessSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_ProcessState); ok {
			return x.ProcessState
		}
	}
	return nil
}

func (x *WebServerFrame) GetWorkspaceActivity() *v1.WorkspaceActivityEvent {
	if x != nil {
		if x, ok := x.Payload.(*WebServerFrame_WorkspaceActivity); ok {
			return x.WorkspaceActivity
		}
	}
	return nil
}

type isWebServerFrame_Payload interface {
	isWebServerFrame_Payload()
}

type WebServerFrame_Hello struct {
	Hello *ServerHello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type WebServerFrame_AgentResponse struct {
	// 直通响应：桌面端返回的 v1 信封（含 error=99 错误臂）。
	AgentResponse *v1.AgentEnvelope `protobuf:"bytes,3,opt,name=agent_response,json=agentResponse,proto3,oneof"`
}

type WebServerFrame_LocalError struct {
	// 网关本地错误（鉴权、校验、离线等；对应 v1 的 type:"error" 信封）。
	LocalError *v1.ErrorResponse `protobuf:"bytes,4,opt,name=local_error,json=localError,proto3,oneof"`
}

type WebServerFrame_Ping struct {
	Ping *PingFrame `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

type WebServerFrame_Status struct {
	// status_get / chat_prepare 的响应与 status 广播共用，新旧客户端共享一个状态归一化器。
	Status *StatusEvent `protobuf:"bytes,6,opt,name=status,proto3,oneof"`
}

type WebServerFrame_ChatSubscribed struct {
	ChatSubscribed *ChatSubscribeResult `protobuf:"bytes,7,opt,name=chat_subscribed,json=chatSubscribed,proto3,oneof"`
}

type WebServerFrame_ChatAccepted struct {
	ChatAccepted *ChatCommandAccepted `protobuf:"bytes,8,opt,name=chat_accepted,json=chatAccepted,proto3,oneof"`
}

type WebServerFrame_ChatActivities struct {
	ChatActivities *ChatActivitiesResult `protobuf:"bytes,9,opt,name=chat_activities,json=chatActivities,proto3,oneof"`
}

type WebServerFrame_ChatEvent struct {
	ChatEvent *ChatStreamEvent `protobuf:"bytes,10,opt,name=chat_event,json=chatEvent,proto3,oneof"`
}

type WebServerFrame_ChatCommandUpdate struct {
	ChatCommandUpdate *ChatCommandUpdate `protobuf:"bytes,11,opt,name=chat_command_update,json=chatCommandUpdate,proto3,oneof"`
}

type WebServerFrame_ChatSubscriptionReset struct {
	ChatSubscriptionReset *ChatSubscriptionReset `protobuf:"bytes,12,opt,name=chat_subscription_reset,json=chatSubscriptionReset,proto3,oneof"`
}

type WebServerFrame_ChatActivity struct {
	ChatActivity *ChatActivityEvent `protobuf:"bytes,13,opt,name=chat_activity,json=chatActivity,proto3,oneof"`
}

type WebServerFrame_Ack struct {
	Ack *AckResult `protobuf:"bytes,14,opt,name=ack,proto3,oneof"`
}

type WebServerFrame_ChatCancelled struct {
	ChatCancelled *ChatCancelResult `protobuf:"bytes,15,opt,name=chat_cancelled,json=chatCancelled,proto3,oneof"`
}

type WebServerFrame_HistoryEvent struct {
	// 广播事件：session 层吐出的 v1 seam 消息零塑形直转。
	HistoryEvent *v1.HistorySyncEvent `protobuf:"bytes,20,opt,name=history_event,json=historyEvent,proto3,oneof"`
}

type WebServerFrame_SettingsEvent struct {
	SettingsEvent *v1.SettingsSyncEvent `protobuf:"bytes,21,opt,name=settings_event,json=settingsEvent,proto3,oneof"`
}

type WebServerFrame_TerminalEvent struct {
	TerminalEvent *v1.TerminalEvent `protobuf:"bytes,22,opt,name=terminal_event,json=terminalEvent,proto3,oneof"`
}

type WebServerFrame_SftpEvent struct {
	SftpEvent *v1.SftpEvent `protobuf:"bytes,23,opt,name=sftp_event,json=sftpEvent,proto3,oneof"`
}

type WebServerFrame_ChatQueueEvent struct {
	ChatQueueEvent *v1.ChatQueueEvent `protobuf:"bytes,24,opt,name=chat_queue_event,json=chatQueueEvent,proto3,oneof"`
}

type WebServerFrame_TunnelState struct {
	TunnelState *v1.TunnelStateSnapshot `protobuf:"bytes,25,opt,name=tunnel_state,json=tunnelState,proto3,oneof"`
}

type WebServerFrame_ProcessState struct {
	ProcessState *v1.ManagedProcessSnapshot `protobuf:"bytes,26,opt,name=process_state,json=processState,proto3,oneof"`
}

type WebServerFrame_WorkspaceActivity struct {
	WorkspaceActivity *v1.WorkspaceActivityEvent `protobuf:"bytes,27,opt,name=workspace_activity,json=workspaceActivity,proto3,oneof"`
}

func (*WebServerFrame_Hello) isWebServerFrame_Payload() {}

func (*WebServerFrame_AgentResponse) isWebServerFrame_Payload() {}

func (*WebServerFrame_LocalError) isWebServerFrame_Payload() {}

func (*WebServerFrame_Ping) isWebServerFrame_Payload() {}

func (*WebServerFrame_Status) isWebServerFrame_Payload() {}

func (*WebServerFrame_ChatSubscribed) isWebServerFrame_Payload() {}

func (*WebServerFrame_ChatAccepted) isWebServerFrame_Payload() {}

func (*WebServerFrame_ChatActivities) isWebServerFrame_Payload() {}

func (*WebServerFrame_ChatEvent) isWebServerFrame_Payload() {}

func (*WebServerFrame_ChatCommandUpdate) isWebServerFrame_Payload() {}

func (*WebServerFrame_ChatSubscriptionReset) isWebServerFrame_Payload() {}

func (*WebServerFrame_ChatActivity) isWebServerFrame_Payload() {}

func (*WebServerFrame_Ack) isWebServerFrame_Payload() {}

func (*WebServerFrame_ChatCancelled) isWebServerFrame_Payload() {}

func (*WebServerFrame_HistoryEvent) isWebServerFrame_Payload() {}

func (*WebServerFrame_SettingsEvent) isWebServerFrame_Payload() {}

func (*WebServerFrame_TerminalEvent) isWebServerFrame_Payload() {}

func (*WebServerFrame_SftpEvent) isWebServerFrame_Payload() {}

func (*WebServerFrame_ChatQueueEvent) isWebServerFrame_Payload() {}

func (*WebServerFrame_TunnelState) isWebServerFrame_Payload() {}

func (*WebServerFrame_ProcessState) isWebServerFrame_Payload() {}

func (*WebServerFrame_WorkspaceActivity) isWebServerFrame_Payload() {}

// AgentClientFrame 为桌面端 → 网关方向的帧。
type AgentClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentClientFrame_Hello
	//	*AgentClientFrame_Envelope
	Payload       isAgentClientFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentClientFrame) Reset() {
	*x = AgentClientFrame{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentClientFrame) ProtoMessage() {}

func (x *AgentClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentClientFrame.ProtoReflect.Descriptor instead.
func (*AgentClientFrame) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{7}
}

func (x *AgentClientFrame) GetPayload() isAgentClientFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentClientFrame) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentClientFrame) GetEnvelope() *v1.AgentEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*AgentClientFrame_Envelope); ok {
			return x.Envelope
		}
	}
	return nil
}

type isAgentClientFrame_Payload interface {
	isAgentClientFrame_Payload()
}

type AgentClientFrame_Hello struct {
	Hello *ClientHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentClientFrame_Envelope struct {
	Envelope *v1.AgentEnvelope `protobuf:"bytes,2,opt,name=envelope,proto3,oneof"`
}

func (*AgentClientFrame_Hello) isAgentClientFrame_Payload() {}

func (*AgentClientFrame_Envelope) isAgentClientFrame_Payload() {}

// AgentServerFrame 为网关 → 桌面端方向的帧。
type AgentServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentServerFrame_Hello
	//	*AgentServerFrame_Envelope
	Payload       isAgentServerFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServerFrame) Reset() {
	*x = AgentServerFrame{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServerFrame) ProtoMessage() {}

func (x *AgentServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServerFrame.ProtoReflect.Descriptor instead.
func (*AgentServerFrame) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{8}
}

func (x *AgentServerFrame) GetPayload() isAgentServerFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentServerFrame) GetHello() *ServerHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentServerFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentServerFrame) GetEnvelope() *v1.GatewayEnvelope {
	if x != nil {
		if x, ok := x.Payload.(*AgentServerFrame_Envelope); ok {
			return x.Envelope
		}
	}
	return nil
}

type isAgentServerFrame_Payload interface {
	isAgentServerFrame_Payload()
}

type AgentServerFrame_Hello struct {
	Hello *ServerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentServerFrame_Envelope struct {
	Envelope *v1.GatewayEnvelope `protobuf:"bytes,2,opt,name=envelope,proto3,oneof"`
}

func (*AgentServerFrame_Hello) isAgentServerFrame_Payload() {}

func (*AgentServerFrame_Envelope) isAgentServerFrame_Payload() {}

// TerminalClientFrame 为客户端（浏览器或桌面端）→ 网关方向的帧。
type TerminalClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TerminalClientFrame_Hello
	//	*TerminalClientFrame_Frame
	Payload       isTerminalClientFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalClientFrame) Reset() {
	*x = TerminalClientFrame{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalClientFrame) ProtoMessage() {}

func (x *TerminalClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalClientFrame.ProtoReflect.Descriptor instead.
func (*TerminalClientFrame) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{9}
}

func (x *TerminalClientFrame) GetPayload() isTerminalClientFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TerminalClientFrame) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*TerminalClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *TerminalClientFrame) GetFrame() *v1.TerminalStreamFrame {
	if x != nil {
		if x, ok := x.Payload.(*TerminalClientFrame_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

type isTerminalClientFrame_Payload interface {
	isTerminalClientFrame_Payload()
}

type TerminalClientFrame_Hello struct {
	Hello *ClientHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type TerminalClientFrame_Frame struct {
	Frame *v1.TerminalStreamFrame `protobuf:"bytes,2,opt,name=frame,proto3,oneof"`
}

func (*TerminalClientFrame_Hello) isTerminalClientFrame_Payload() {}

func (*TerminalClientFrame_Frame) isTerminalClientFrame_Payload() {}

// TerminalServerFrame 为网关 → 客户端方向的帧。
type TerminalServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TerminalServerFrame_Hello
	//	*TerminalServerFrame_Frame
	Payload       isTerminalServerFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalServerFrame) Reset() {
	*x = TerminalServerFrame{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalServerFrame) ProtoMessage() {}

func (x *TerminalServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalServerFrame.ProtoReflect.Descriptor instead.
func (*TerminalServerFrame) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{10}
}

func (x *TerminalServerFrame) GetPayload() isTerminalServerFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TerminalServerFrame) GetHello() *ServerHello {
	if x != nil {
		if x, ok := x.Payload.(*TerminalServerFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *TerminalServerFrame) GetFrame() *v1.TerminalStreamFrame {
	if x != nil {
		if x, ok := x.Payload.(*TerminalServerFrame_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

type isTerminalServerFrame_Payload interface {
	isTerminalServerFrame_Payload()
}

type TerminalServerFrame_Hello struct {
	Hello *ServerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type TerminalServerFrame_Frame struct {
	Frame *v1.TerminalStreamFrame `protobuf:"bytes,2,opt,name=frame,proto3,oneof"`
}

func (*TerminalServerFrame_Hello) isTerminalServerFrame_Payload() {}

func (*TerminalServerFrame_Frame) isTerminalServerFrame_Payload() {}

// StatusGetRequest 请求网关侧运行状态快照（对应 v1 "status.get"）。
type StatusGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusGetRequest) Reset() {
	*x = StatusGetRequest{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusGetRequest) ProtoMessage() {}

func (x *StatusGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusGetRequest.ProtoReflect.Descriptor instead.
func (*StatusGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{11}
}

// StatusEvent 镜像 session.Status 的 JSON 形状（字段一一对应）。
type StatusEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Online                bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	AgentReady            bool                   `protobuf:"varint,2,opt,name=agent_ready,json=agentReady,proto3" json:"agent_ready,omitempty"`
	ChatRuntimeReady      bool                   `protobuf:"varint,3,opt,name=chat_runtime_ready,json=chatRuntimeReady,proto3" json:"chat_runtime_ready,omitempty"`
	AgentId               string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion          string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	SessionId             string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ConnectedSince        int64                  `protobuf:"varint,7,opt,name=connected_since,json=connectedSince,proto3" json:"connected_since,omitempty"`
	LastHeartbeat         int64                  `protobuf:"varint,8,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	RuntimeState          string                 `protobuf:"bytes,9,opt,name=runtime_state,json=runtimeState,proto3" json:"runtime_state,omitempty"`
	RuntimeLastHeartbeat  int64                  `protobuf:"varint,10,opt,name=runtime_last_heartbeat,json=runtimeLastHeartbeat,proto3" json:"runtime_last_heartbeat,omitempty"`
	RuntimeWorkerId       string                 `protobuf:"bytes,11,opt,name=runtime_worker_id,json=runtimeWorkerId,proto3" json:"runtime_worker_id,omitempty"`
	RuntimeVisible        bool                   `protobuf:"varint,12,opt,name=runtime_visible,json=runtimeVisible,proto3" json:"runtime_visible,omitempty"`
	RuntimeActiveRunCount uint32                 `protobuf:"varint,13,opt,name=runtime_active_run_count,json=runtimeActiveRunCount,proto3" json:"runtime_active_run_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{12}
}

func (x *StatusEvent) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *StatusEvent) GetAgentReady() bool {
	if x != nil {
		return x.AgentReady
	}
	return false
}

func (x *StatusEvent) GetChatRuntimeReady() bool {
	if x != nil {
		return x.ChatRuntimeReady
	}
	return false
}

func (x *StatusEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusEvent) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *StatusEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StatusEvent) GetConnectedSince() int64 {
	if x != nil {
		return x.ConnectedSince
	}
	return 0
}

func (x *StatusEvent) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *StatusEvent) GetRuntimeState() string {
	if x != nil {
		return x.RuntimeState
	}
	return ""
}

func (x *StatusEvent) GetRuntimeLastHeartbeat() int64 {
	if x != nil {
		return x.RuntimeLastHeartbeat
	}
	return 0
}

func (x *StatusEvent) GetRuntimeWorkerId() string {
	if x != nil {
		return x.RuntimeWorkerId
	}
	return ""
}

func (x *StatusEvent) GetRuntimeVisible() bool {
	if x != nil {
		return x.RuntimeVisible
	}
	return false
}

func (x *StatusEvent) GetRuntimeActiveRunCount() uint32 {
	if x != nil {
		return x.RuntimeActiveRunCount
	}
	return 0
}

// ChatPrepareRequest 唤醒/探活桌面端 chat 运行时（对应 v1 "chat.prepare"）；响应为 StatusEvent。
type ChatPrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPrepareRequest) Reset() {
	*x = ChatPrepareRequest{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPrepareRequest) ProtoMessage() {}

func (x *ChatPrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPrepareRequest.ProtoReflect.Descriptor instead.
func (*ChatPrepareRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{13}
}

func (x *ChatPrepareRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ChatSubscribeRequest 订阅会话事件流（对应 v1 "chat.subscribe"）。after_seq + stream_epoch
// 支持断线重放：epoch 不匹配或序号超界时服务端置 reset 并从头回放。
type ChatSubscribeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AfterSeq       int64                  `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	StreamEpoch    string                 `protobuf:"bytes,3,opt,name=stream_epoch,json=streamEpoch,proto3" json:"stream_epoch,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatSubscribeRequest) Reset() {
	*x = ChatSubscribeRequest{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSubscribeRequest) ProtoMessage() {}

func (x *ChatSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSubscribeRequest.ProtoReflect.Descriptor instead.
func (*ChatSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{14}
}

func (x *ChatSubscribeRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatSubscribeRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ChatSubscribeRequest) GetStreamEpoch() string {
	if x != nil {
		return x.StreamEpoch
	}
	return ""
}

// ChatRunActivity 镜像 session.RunActivity 的 JSON 形状。
type ChatRunActivity struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RunId      string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	State      string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	StartedSeq int64                  `protobuf:"varint,3,opt,name=started_seq,json=startedSeq,proto3" json:"started_seq,omitempty"`
	// Unix 毫秒时间戳。
	UpdatedAtMs            int64  `protobuf:"varint,4,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	ToolStatus             string `protobuf:"bytes,5,opt,name=tool_status,json=toolStatus,proto3" json:"tool_status,omitempty"`
	ToolStatusIsCompaction bool   `protobuf:"varint,6,opt,name=tool_status_is_compaction,json=toolStatusIsCompaction,proto3" json:"tool_status_is_compaction,omitempty"`
	ClientRequestId        string `protobuf:"bytes,7,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	// 以下两个字段仅在 chat_activities 列表中填充。
	ConversationId string `protobuf:"bytes,8,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Workdir        string `protobuf:"bytes,9,opt,name=workdir,proto3" json:"workdir,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatRunActivity) Reset() {
	*x = ChatRunActivity{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRunActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRunActivity) ProtoMessage() {}

func (x *ChatRunActivity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRunActivity.ProtoReflect.Descriptor instead.
func (*ChatRunActivity) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{15}
}

func (x *ChatRunActivity) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ChatRunActivity) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ChatRunActivity) GetStartedSeq() int64 {
	if x != nil {
		return x.StartedSeq
	}
	return 0
}

func (x *ChatRunActivity) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

func (x *ChatRunActivity) GetToolStatus() string {
	if x != nil {
		return x.ToolStatus
	}
	return ""
}

func (x *ChatRunActivity) GetToolStatusIsCompaction() bool {
	if x != nil {
		return x.ToolStatusIsCompaction
	}
	return false
}

func (x *ChatRunActivity) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

func (x *ChatRunActivity) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatRunActivity) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

// ChatRunSnapshot 镜像 session.RunSnapshot 的 JSON 形状。
type ChatRunSnapshot struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RunId    string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Revision int64                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// 桌面端渲染快照，内容为动态 JSON（与 v1 一致按字符串携带，不建模）。
	EntriesJson            string `protobuf:"bytes,3,opt,name=entries_json,json=entriesJson,proto3" json:"entries_json,omitempty"`
	ToolStatus             string `protobuf:"bytes,4,opt,name=tool_status,json=toolStatus,proto3" json:"tool_status,omitempty"`
	ToolStatusIsCompaction bool   `protobuf:"varint,5,opt,name=tool_status_is_compaction,json=toolStatusIsCompaction,proto3" json:"tool_status_is_compaction,omitempty"`
	AsOfSeq                int64  `protobuf:"varint,6,opt,name=as_of_seq,json=asOfSeq,proto3" json:"as_of_seq,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ChatRunSnapshot) Reset() {
	*x = ChatRunSnapshot{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRunSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRunSnapshot) ProtoMessage() {}

func (x *ChatRunSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRunSnapshot.ProtoReflect.Descriptor instead.
func (*ChatRunSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{16}
}

func (x *ChatRunSnapshot) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ChatRunSnapshot) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ChatRunSnapshot) GetEntriesJson() string {
	if x != nil {
		return x.EntriesJson
	}
	return ""
}

func (x *ChatRunSnapshot) GetToolStatus() string {
	if x != nil {
		return x.ToolStatus
	}
	return ""
}

func (x *ChatRunSnapshot) GetToolStatusIsCompaction() bool {
	if x != nil {
		return x.ToolStatusIsCompaction
	}
	return false
}

func (x *ChatRunSnapshot) GetAsOfSeq() int64 {
	if x != nil {
		return x.AsOfSeq
	}
	return 0
}

// ChatSubscribeResult 是 chat_subscribe 的响应。
type ChatSubscribeResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	StreamEpoch    string                 `protobuf:"bytes,2,opt,name=stream_epoch,json=streamEpoch,proto3" json:"stream_epoch,omitempty"`
	LatestSeq      int64                  `protobuf:"varint,3,opt,name=latest_seq,json=latestSeq,proto3" json:"latest_seq,omitempty"`
	Reset_         bool                   `protobuf:"varint,4,opt,name=reset,proto3" json:"reset,omitempty"`
	Activity       *ChatRunActivity       `protobuf:"bytes,5,opt,name=activity,proto3" json:"activity,omitempty"`
	Snapshot       *ChatRunSnapshot       `protobuf:"bytes,6,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// 回放的事件序列。载荷由 chatwire 塑形为深度动态 JSON，与 v1 一致按字节携带、不 proto 化
	// （重建模会分叉 chatwire 且对压缩后的二进制帧无实际收益）。
	EventsJson    [][]byte `protobuf:"bytes,7,rep,name=events_json,json=eventsJson,proto3" json:"events_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSubscribeResult) Reset() {
	*x = ChatSubscribeResult{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSubscribeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSubscribeResult) ProtoMessage() {}

func (x *ChatSubscribeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSubscribeResult.ProtoReflect.Descriptor instead.
func (*ChatSubscribeResult) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{17}
}

func (x *ChatSubscribeResult) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatSubscribeResult) GetStreamEpoch() string {
	if x != nil {
		return x.StreamEpoch
	}
	return ""
}

func (x *ChatSubscribeResult) GetLatestSeq() int64 {
	if x != nil {
		return x.LatestSeq
	}
	return 0
}

func (x *ChatSubscribeResult) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

func (x *ChatSubscribeResult) GetActivity() *ChatRunActivity {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *ChatSubscribeResult) GetSnapshot() *ChatRunSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ChatSubscribeResult) GetEventsJson() [][]byte {
	if x != nil {
		return x.EventsJson
	}
	return nil
}

// ChatUnsubscribeRequest 取消订阅（对应 v1 "chat.unsubscribe"）；响应 AckResult。
type ChatUnsubscribeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatUnsubscribeRequest) Reset() {
	*x = ChatUnsubscribeRequest{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUnsubscribeRequest) ProtoMessage() {}

func (x *ChatUnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*ChatUnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{18}
}

func (x *ChatUnsubscribeRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// ChatActivitiesRequest 查询运行中会话（对应 v1 "chat.activities"）；仅由网关状态应答，桌面端离线时亦可用。
type ChatActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatActivitiesRequest) Reset() {
	*x = ChatActivitiesRequest{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatActivitiesRequest) ProtoMessage() {}

func (x *ChatActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatActivitiesRequest.ProtoReflect.Descriptor instead.
func (*ChatActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{19}
}

type ChatActivitiesResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RunningConversations []*ChatRunActivity     `protobuf:"bytes,1,rep,name=running_conversations,json=runningConversations,proto3" json:"running_conversations,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChatActivitiesResult) Reset() {
	*x = ChatActivitiesResult{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatActivitiesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatActivitiesResult) ProtoMessage() {}

func (x *ChatActivitiesResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatActivitiesResult.ProtoReflect.Descriptor instead.
func (*ChatActivitiesResult) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{20}
}

func (x *ChatActivitiesResult) GetRunningConversations() []*ChatRunActivity {
	if x != nil {
		return x.RunningConversations
	}
	return nil
}

// ChatStreamEvent 是订阅后推送的单条会话事件。
type ChatStreamEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// 事件序号（与 payload_json 内的 seq 一致，便于不解析载荷即可去重）。
	Seq           int64  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	PayloadJson   []byte `protobuf:"bytes,3,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamEvent) Reset() {
	*x = ChatStreamEvent{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamEvent) ProtoMessage() {}

func (x *ChatStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamEvent.ProtoReflect.Descriptor instead.
func (*ChatStreamEvent) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{21}
}

func (x *ChatStreamEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatStreamEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ChatStreamEvent) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

// ChatCommandAccepted 是 chat_command 提交被接受的响应（对应 v1 chat.command 的应答形状）。
type ChatCommandAccepted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	AcceptedSeq    int64                  `protobuf:"varint,3,opt,name=accepted_seq,json=acceptedSeq,proto3" json:"accepted_seq,omitempty"`
	Deduped        bool                   `protobuf:"varint,4,opt,name=deduped,proto3" json:"deduped,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatCommandAccepted) Reset() {
	*x = ChatCommandAccepted{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCommandAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCommandAccepted) ProtoMessage() {}

func (x *ChatCommandAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCommandAccepted.ProtoReflect.Descriptor instead.
func (*ChatCommandAccepted) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{22}
}

func (x *ChatCommandAccepted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ChatCommandAccepted) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatCommandAccepted) GetAcceptedSeq() int64 {
	if x != nil {
		return x.AcceptedSeq
	}
	return 0
}

func (x *ChatCommandAccepted) GetDeduped() bool {
	if x != nil {
		return x.Deduped
	}
	return false
}

// ChatCommandUpdate 推送命令的前置阶段结果（bound / queued_in_gui / failed），镜像 session.ChatCommandUpdate。
type ChatCommandUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RunId           string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ClientRequestId string                 `protobuf:"bytes,2,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	ConversationId  string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Phase           string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message         string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatCommandUpdate) Reset() {
	*x = ChatCommandUpdate{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCommandUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCommandUpdate) ProtoMessage() {}

func (x *ChatCommandUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCommandUpdate.ProtoReflect.Descriptor instead.
func (*ChatCommandUpdate) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{23}
}

func (x *ChatCommandUpdate) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ChatCommandUpdate) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

func (x *ChatCommandUpdate) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatCommandUpdate) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ChatCommandUpdate) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ChatCommandUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ChatSubscriptionReset 通知客户端某会话流已被限流丢弃，需重新订阅（after_seq 断点续传）。
type ChatSubscriptionReset struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatSubscriptionReset) Reset() {
	*x = ChatSubscriptionReset{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSubscriptionReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSubscriptionReset) ProtoMessage() {}

func (x *ChatSubscriptionReset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSubscriptionReset.ProtoReflect.Descriptor instead.
func (*ChatSubscriptionReset) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{24}
}

func (x *ChatSubscriptionReset) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// ChatCancelResult 是 chat.cancel 的响应。
type ChatCancelResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RunId          string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChatCancelResult) Reset() {
	*x = ChatCancelResult{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCancelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCancelResult) ProtoMessage() {}

func (x *ChatCancelResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCancelResult.ProtoReflect.Descriptor instead.
func (*ChatCancelResult) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{25}
}

func (x *ChatCancelResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ChatCancelResult) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ChatCancelResult) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

// ChatActivityEvent 广播会话活动状态变化，镜像 session.ConversationActivityEvent。
type ChatActivityEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConversationId  string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RunId           string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ClientRequestId string                 `protobuf:"bytes,3,opt,name=client_request_id,json=clientRequestId,proto3" json:"client_request_id,omitempty"`
	Running         bool                   `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	State           string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Workdir         string                 `protobuf:"bytes,6,opt,name=workdir,proto3" json:"workdir,omitempty"`
	UpdatedAtMs     int64                  `protobuf:"varint,7,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatActivityEvent) Reset() {
	*x = ChatActivityEvent{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatActivityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatActivityEvent) ProtoMessage() {}

func (x *ChatActivityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatActivityEvent.ProtoReflect.Descriptor instead.
func (*ChatActivityEvent) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{26}
}

func (x *ChatActivityEvent) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatActivityEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ChatActivityEvent) GetClientRequestId() string {
	if x != nil {
		return x.ClientRequestId
	}
	return ""
}

func (x *ChatActivityEvent) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ChatActivityEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ChatActivityEvent) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

func (x *ChatActivityEvent) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

// WorkspaceSubscribeRequest 订阅工作区活动（对应 v1 "workspace.subscribe"）；响应 AckResult，事件经 workspace_activity 臂广播。
type WorkspaceSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workdir       string                 `protobuf:"bytes,1,opt,name=workdir,proto3" json:"workdir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceSubscribeRequest) Reset() {
	*x = WorkspaceSubscribeRequest{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceSubscribeRequest) ProtoMessage() {}

func (x *WorkspaceSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceSubscribeRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{27}
}

func (x *WorkspaceSubscribeRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

// WorkspaceUnsubscribeRequest 取消订阅；响应 AckResult。
type WorkspaceUnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workdir       string                 `protobuf:"bytes,1,opt,name=workdir,proto3" json:"workdir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceUnsubscribeRequest) Reset() {
	*x = WorkspaceUnsubscribeRequest{}
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceUnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceUnsubscribeRequest) ProtoMessage() {}

func (x *WorkspaceUnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v2_gateway_ws_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceUnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*WorkspaceUnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_v2_gateway_ws_proto_rawDescGZIP(), []int{28}
}

func (x *WorkspaceUnsubscribeRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

var File_proto_v2_gateway_ws_proto protoreflect.FileDescriptor

const file_proto_v2_gateway_ws_proto_rawDesc = "" +
	"\n" +
	"\x19proto/v2/gateway_ws.proto\x12\x14liveagent.gateway.v2\x1a\x16proto/v1/gateway.proto\"\x8c\x02\n" +
	"\vClientHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x124\n" +
	"\x04role\x18\x02 \x01(\x0e2 .liveagent.gateway.v2.ClientRoleR\x04role\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x1f\n" +
	"\vclient_name\x18\x06 \x01(\tR\n" +
	"clientName\x12%\n" +
	"\x0eclient_version\x18\a \x01(\tR\rclientVersion\"\xdd\x01\n" +
	"\vServerHello\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vserver_time\x18\x04 \x01(\x03R\n" +
	"serverTime\x128\n" +
	"\x18heartbeat_period_seconds\x18\x05 \x01(\rR\x16heartbeatPeriodSeconds\x12*\n" +
	"\x11max_message_bytes\x18\x06 \x01(\x04R\x0fmaxMessageBytes\")\n" +
	"\tPingFrame\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\")\n" +
	"\tPongFrame\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x1b\n" +
	"\tAckResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xb7\a\n" +
	"\x0eWebClientFrame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x129\n" +
	"\x05hello\x18\x02 \x01(\v2!.liveagent.gateway.v2.ClientHelloH\x00R\x05hello\x12L\n" +
	"\ragent_request\x18\x03 \x01(\v2%.liveagent.gateway.v1.GatewayEnvelopeH\x00R\fagentRequest\x12G\n" +
	"\n" +
	"status_get\x18\x04 \x01(\v2&.liveagent.gateway.v2.StatusGetRequestH\x00R\tstatusGet\x12M\n" +
	"\fchat_command\x18\x05 \x01(\v2(.liveagent.gateway.v1.ChatCommandRequestH\x00R\vchatCommand\x12M\n" +
	"\fchat_prepare\x18\x06 \x01(\v2(.liveagent.gateway.v2.ChatPrepareRequestH\x00R\vchatPrepare\x12S\n" +
	"\x0echat_subscribe\x18\a \x01(\v2*.liveagent.gateway.v2.ChatSubscribeRequestH\x00R\rchatSubscribe\x12Y\n" +
	"\x10chat_unsubscribe\x18\b \x01(\v2,.liveagent.gateway.v2.ChatUnsubscribeRequestH\x00R\x0fchatUnsubscribe\x12V\n" +
	"\x0fchat_activities\x18\t \x01(\v2+.liveagent.gateway.v2.ChatActivitiesRequestH\x00R\x0echatActivities\x12b\n" +
	"\x13workspace_subscribe\x18\n" +
	" \x01(\v2/.liveagent.gateway.v2.WorkspaceSubscribeRequestH\x00R\x12workspaceSubscribe\x12h\n" +
	"\x15workspace_unsubscribe\x18\v \x01(\v21.liveagent.gateway.v2.WorkspaceUnsubscribeRequestH\x00R\x14workspaceUnsubscribe\x125\n" +
	"\x04pong\x18\f \x01(\v2\x1f.liveagent.gateway.v2.PongFrameH\x00R\x04pongB\t\n" +
	"\apayload\"\xe5\r\n" +
	"\x0eWebServerFrame\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x129\n" +
	"\x05hello\x18\x02 \x01(\v2!.liveagent.gateway.v2.ServerHelloH\x00R\x05hello\x12L\n" +
	"\x0eagent_response\x18\x03 \x01(\v2#.liveagent.gateway.v1.AgentEnvelopeH\x00R\ragentResponse\x12F\n" +
	"\vlocal_error\x18\x04 \x01(\v2#.liveagent.gateway.v1.ErrorResponseH\x00R\n" +
	"localError\x125\n" +
	"\x04ping\x18\x05 \x01(\v2\x1f.liveagent.gateway.v2.PingFrameH\x00R\x04ping\x12;\n" +
	"\x06status\x18\x06 \x01(\v2!.liveagent.gateway.v2.StatusEventH\x00R\x06status\x12T\n" +
	"\x0fchat_subscribed\x18\a \x01(\v2).liveagent.gateway.v2.ChatSubscribeResultH\x00R\x0echatSubscribed\x12P\n" +
	"\rchat_accepted\x18\b \x01(\v2).liveagent.gateway.v2.ChatCommandAcceptedH\x00R\fchatAccepted\x12U\n" +
	"\x0fchat_activities\x18\t \x01(\v2*.liveagent.gateway.v2.ChatActivitiesResultH\x00R\x0echatActivities\x12F\n" +
	"\n" +
	"chat_event\x18\n" +
	" \x01(\v2%.liveagent.gateway.v2.ChatStreamEventH\x00R\tchatEvent\x12Y\n" +
	"\x13chat_command_update\x18\v \x01(\v2'.liveagent.gateway.v2.ChatCommandUpdateH\x00R\x11chatCommandUpdate\x12e\n" +
	"\x17chat_subscription_reset\x18\f \x01(\v2+.liveagent.gateway.v2.ChatSubscriptionResetH\x00R\x15chatSubscriptionReset\x12N\n" +
	"\rchat_activity\x18\r \x01(\v2'.liveagent.gateway.v2.ChatActivityEventH\x00R\fchatActivity\x123\n" +
	"\x03ack\x18\x0e \x01(\v2\x1f.liveagent.gateway.v2.AckResultH\x00R\x03ack\x12O\n" +
	"\x0echat_cancelled\x18\x0f \x01(\v2&.liveagent.gateway.v2.ChatCancelResultH\x00R\rchatCancelled\x12M\n" +
	"\rhistory_event\x18\x14 \x01(\v2&.liveagent.gateway.v1.HistorySyncEventH\x00R\fhistoryEvent\x12P\n" +
	"\x0esettings_event\x18\x15 \x01(\v2'.liveagent.gateway.v1.SettingsSyncEventH\x00R\rsettingsEvent\x12L\n" +
	"\x0eterminal_event\x18\x16 \x01(\v2#.liveagent.gateway.v1.TerminalEventH\x00R\rterminalEvent\x12@\n" +
	"\n" +
	"sftp_event\x18\x17 \x01(\v2\x1f.liveagent.gateway.v1.SftpEventH\x00R\tsftpEvent\x12P\n" +
	"\x10chat_queue_event\x18\x18 \x01(\v2$.liveagent.gateway.v1.ChatQueueEventH\x00R\x0echatQueueEvent\x12N\n" +
	"\ftunnel_state\x18\x19 \x01(\v2).liveagent.gateway.v1.TunnelStateSnapshotH\x00R\vtunnelState\x12S\n" +
	"\rprocess_state\x18\x1a \x01(\v2,.liveagent.gateway.v1.ManagedProcessSnapshotH\x00R\fprocessState\x12]\n" +
	"\x12workspace_activity\x18\x1b \x01(\v2,.liveagent.gateway.v1.WorkspaceActivityEventH\x00R\x11workspaceActivityB\t\n" +
	"\apayload\"\x9b\x01\n" +
	"\x10AgentClientFrame\x129\n" +
	"\x05hello\x18\x01 \x01(\v2!.liveagent.gateway.v2.ClientHelloH\x00R\x05hello\x12A\n" +
	"\benvelope\x18\x02 \x01(\v2#.liveagent.gateway.v1.AgentEnvelopeH\x00R\benvelopeB\t\n" +
	"\apayload\"\x9d\x01\n" +
	"\x10AgentServerFrame\x129\n" +
	"\x05hello\x18\x01 \x01(\v2!.liveagent.gateway.v2.ServerHelloH\x00R\x05hello\x12C\n" +
	"\benvelope\x18\x02 \x01(\v2%.liveagent.gateway.v1.GatewayEnvelopeH\x00R\benvelopeB\t\n" +
	"\apayload\"\x9e\x01\n" +
	"\x13TerminalClientFrame\x129\n" +
	"\x05hello\x18\x01 \x01(\v2!.liveagent.gateway.v2.ClientHelloH\x00R\x05hello\x12A\n" +
	"\x05frame\x18\x02 \x01(\v2).liveagent.gateway.v1.TerminalStreamFrameH\x00R\x05frameB\t\n" +
	"\apayload\"\x9e\x01\n" +
	"\x13TerminalServerFrame\x129\n" +
	"\x05hello\x18\x01 \x01(\v2!.liveagent.gateway.v2.ServerHelloH\x00R\x05hello\x12A\n" +
	"\x05frame\x18\x02 \x01(\v2).liveagent.gateway.v1.TerminalStreamFrameH\x00R\x05frameB\t\n" +
	"\apayload\"\x12\n" +
	"\x10StatusGetRequest\"\x8c\x04\n" +
	"\vStatusEvent\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12\x1f\n" +
	"\vagent_ready\x18\x02 \x01(\bR\n" +
	"agentReady\x12,\n" +
	"\x12chat_runtime_ready\x18\x03 \x01(\bR\x10chatRuntimeReady\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12'\n" +
	"\x0fconnected_since\x18\a \x01(\x03R\x0econnectedSince\x12%\n" +
	"\x0elast_heartbeat\x18\b \x01(\x03R\rlastHeartbeat\x12#\n" +
	"\rruntime_state\x18\t \x01(\tR\fruntimeState\x124\n" +
	"\x16runtime_last_heartbeat\x18\n" +
	" \x01(\x03R\x14runtimeLastHeartbeat\x12*\n" +
	"\x11runtime_worker_id\x18\v \x01(\tR\x0fruntimeWorkerId\x12'\n" +
	"\x0fruntime_visible\x18\f \x01(\bR\x0eruntimeVisible\x127\n" +
	"\x18runtime_active_run_count\x18\r \x01(\rR\x15runtimeActiveRunCount\",\n" +
	"\x12ChatPrepareRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x7f\n" +
	"\x14ChatSubscribeRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x03R\bafterSeq\x12!\n" +
	"\fstream_epoch\x18\x03 \x01(\tR\vstreamEpoch\"\xce\x02\n" +
	"\x0fChatRunActivity\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vstarted_seq\x18\x03 \x01(\x03R\n" +
	"startedSeq\x12\"\n" +
	"\rupdated_at_ms\x18\x04 \x01(\x03R\vupdatedAtMs\x12\x1f\n" +
	"\vtool_status\x18\x05 \x01(\tR\n" +
	"toolStatus\x129\n" +
	"\x19tool_status_is_compaction\x18\x06 \x01(\bR\x16toolStatusIsCompaction\x12*\n" +
	"\x11client_request_id\x18\a \x01(\tR\x0fclientRequestId\x12'\n" +
	"\x0fconversation_id\x18\b \x01(\tR\x0econversationId\x12\x18\n" +
	"\aworkdir\x18\t \x01(\tR\aworkdir\"\xdf\x01\n" +
	"\x0fChatRunSnapshot\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\x12!\n" +
	"\fentries_json\x18\x03 \x01(\tR\ventriesJson\x12\x1f\n" +
	"\vtool_status\x18\x04 \x01(\tR\n" +
	"toolStatus\x129\n" +
	"\x19tool_status_is_compaction\x18\x05 \x01(\bR\x16toolStatusIsCompaction\x12\x1a\n" +
	"\tas_of_seq\x18\x06 \x01(\x03R\aasOfSeq\"\xbd\x02\n" +
	"\x13ChatSubscribeResult\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12!\n" +
	"\fstream_epoch\x18\x02 \x01(\tR\vstreamEpoch\x12\x1d\n" +
	"\n" +
	"latest_seq\x18\x03 \x01(\x03R\tlatestSeq\x12\x14\n" +
	"\x05reset\x18\x04 \x01(\bR\x05reset\x12A\n" +
	"\bactivity\x18\x05 \x01(\v2%.liveagent.gateway.v2.ChatRunActivityR\bactivity\x12A\n" +
	"\bsnapshot\x18\x06 \x01(\v2%.liveagent.gateway.v2.ChatRunSnapshotR\bsnapshot\x12\x1f\n" +
	"\vevents_json\x18\a \x03(\fR\n" +
	"eventsJson\"A\n" +
	"\x16ChatUnsubscribeRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"\x17\n" +
	"\x15ChatActivitiesRequest\"r\n" +
	"\x14ChatActivitiesResult\x12Z\n" +
	"\x15running_conversations\x18\x01 \x03(\v2%.liveagent.gateway.v2.ChatRunActivityR\x14runningConversations\"o\n" +
	"\x0fChatStreamEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12!\n" +
	"\fpayload_json\x18\x03 \x01(\fR\vpayloadJson\"\x92\x01\n" +
	"\x13ChatCommandAccepted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12!\n" +
	"\faccepted_seq\x18\x03 \x01(\x03R\vacceptedSeq\x12\x18\n" +
	"\adeduped\x18\x04 \x01(\bR\adeduped\"\xce\x01\n" +
	"\x11ChatCommandUpdate\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12*\n" +
	"\x11client_request_id\x18\x02 \x01(\tR\x0fclientRequestId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"@\n" +
	"\x15ChatSubscriptionReset\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\"b\n" +
	"\x10ChatCancelResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\"\xed\x01\n" +
	"\x11ChatActivityEvent\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12*\n" +
	"\x11client_request_id\x18\x03 \x01(\tR\x0fclientRequestId\x12\x18\n" +
	"\arunning\x18\x04 \x01(\bR\arunning\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\aworkdir\x18\x06 \x01(\tR\aworkdir\x12\"\n" +
	"\rupdated_at_ms\x18\a \x01(\x03R\vupdatedAtMs\"5\n" +
	"\x19WorkspaceSubscribeRequest\x12\x18\n" +
	"\aworkdir\x18\x01 \x01(\tR\aworkdir\"7\n" +
	"\x1bWorkspaceUnsubscribeRequest\x12\x18\n" +
	"\aworkdir\x18\x01 \x01(\tR\aworkdir*Y\n" +
	"\n" +
	"ClientRole\x12\x1b\n" +
	"\x17CLIENT_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CLIENT_ROLE_BROWSER\x10\x01\x12\x15\n" +
	"\x11CLIENT_ROLE_AGENT\x10\x02B@Z>github.com/liveagent/agent-gateway/internal/proto/v2;gatewayv2b\x06proto3"

var (
	file_proto_v2_gateway_ws_proto_rawDescOnce sync.Once
	file_proto_v2_gateway_ws_proto_rawDescData []byte
)

func file_proto_v2_gateway_ws_proto_rawDescGZIP() []byte {
	file_proto_v2_gateway_ws_proto_rawDescOnce.Do(func() {
		file_proto_v2_gateway_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v2_gateway_ws_proto_rawDesc), len(file_proto_v2_gateway_ws_proto_rawDesc)))
	})
	return file_proto_v2_gateway_ws_proto_rawDescData
}

var file_proto_v2_gateway_ws_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_v2_gateway_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_v2_gateway_ws_proto_goTypes = []any{
	(ClientRole)(0),                     // 0: liveagent.gateway.v2.ClientRole
	(*ClientHello)(nil),                 // 1: liveagent.gateway.v2.ClientHello
	(*ServerHello)(nil),                 // 2: liveagent.gateway.v2.ServerHello
	(*PingFrame)(nil),                   // 3: liveagent.gateway.v2.PingFrame
	(*PongFrame)(nil),                   // 4: liveagent.gateway.v2.PongFrame
	(*AckResult)(nil),                   // 5: liveagent.gateway.v2.AckResult
	(*WebClientFrame)(nil),              // 6: liveagent.gateway.v2.WebClientFrame
	(*WebServerFrame)(nil),              // 7: liveagent.gateway.v2.WebServerFrame
	(*AgentClientFrame)(nil),            // 8: liveagent.gateway.v2.AgentClientFrame
	(*AgentServerFrame)(nil),            // 9: liveagent.gateway.v2.AgentServerFrame
	(*TerminalClientFrame)(nil),         // 10: liveagent.gateway.v2.TerminalClientFrame
	(*TerminalServerFrame)(nil),         // 11: liveagent.gateway.v2.TerminalServerFrame
	(*StatusGetRequest)(nil),            // 12: liveagent.gateway.v2.StatusGetRequest
	(*StatusEvent)(nil),                 // 13: liveagent.gateway.v2.StatusEvent
	(*ChatPrepareRequest)(nil),          // 14: liveagent.gateway.v2.ChatPrepareRequest
	(*ChatSubscribeRequest)(nil),        // 15: liveagent.gateway.v2.ChatSubscribeRequest
	(*ChatRunActivity)(nil),             // 16: liveagent.gateway.v2.ChatRunActivity
	(*ChatRunSnapshot)(nil),             // 17: liveagent.gateway.v2.ChatRunSnapshot
	(*ChatSubscribeResult)(nil),         // 18: liveagent.gateway.v2.ChatSubscribeResult
	(*ChatUnsubscribeRequest)(nil),      // 19: liveagent.gateway.v2.ChatUnsubscribeRequest
	(*ChatActivitiesRequest)(nil),       // 20: liveagent.gateway.v2.ChatActivitiesRequest
	(*ChatActivitiesResult)(nil),        // 21: liveagent.gateway.v2.ChatActivitiesResult
	(*ChatStreamEvent)(nil),             // 22: liveagent.gateway.v2.ChatStreamEvent
	(*ChatCommandAccepted)(nil),         // 23: liveagent.gateway.v2.ChatCommandAccepted
	(*ChatCommandUpdate)(nil),           // 24: liveagent.gateway.v2.ChatCommandUpdate
	(*ChatSubscriptionReset)(nil),       // 25: liveagent.gateway.v2.ChatSubscriptionReset
	(*ChatCancelResult)(nil),            // 26: liveagent.gateway.v2.ChatCancelResult
	(*ChatActivityEvent)(nil),           // 27: liveagent.gateway.v2.ChatActivityEvent
	(*WorkspaceSubscribeRequest)(nil),   // 28: liveagent.gateway.v2.WorkspaceSubscribeRequest
	(*WorkspaceUnsubscribeRequest)(nil), // 29: liveagent.gateway.v2.WorkspaceUnsubscribeRequest
	(*v1.GatewayEnvelope)(nil),          // 30: liveagent.gateway.v1.GatewayEnvelope
	(*v1.ChatCommandRequest)(nil),       // 31: liveagent.gateway.v1.ChatCommandRequest
	(*v1.AgentEnvelope)(nil),            // 32: liveagent.gateway.v1.AgentEnvelope
	(*v1.ErrorResponse)(nil),            // 33: liveagent.gateway.v1.ErrorResponse
	(*v1.HistorySyncEvent)(nil),         // 34: liveagent.gateway.v1.HistorySyncEvent
	(*v1.SettingsSyncEvent)(nil),        // 35: liveagent.gateway.v1.SettingsSyncEvent
	(*v1.TerminalEvent)(nil),            // 36: liveagent.gateway.v1.TerminalEvent
	(*v1.SftpEvent)(nil),                // 37: liveagent.gateway.v1.SftpEvent
	(*v1.ChatQueueEvent)(nil),           // 38: liveagent.gateway.v1.ChatQueueEvent
	(*v1.TunnelStateSnapshot)(nil),      // 39: liveagent.gateway.v1.TunnelStateSnapshot
	(*v1.ManagedProcessSnapshot)(nil),   // 40: liveagent.gateway.v1.ManagedProcessSnapshot
	(*v1.WorkspaceActivityEvent)(nil),   // 41: liveagent.gateway.v1.WorkspaceActivityEvent
	(*v1.TerminalStreamFrame)(nil),      // 42: liveagent.gateway.v1.TerminalStreamFrame
}
var file_proto_v2_gateway_ws_proto_depIdxs = []int32{
	0,  // 0: liveagent.gateway.v2.ClientHello.role:type_name -> liveagent.gateway.v2.ClientRole
	1,  // 1: liveagent.gateway.v2.WebClientFrame.hello:type_name -> liveagent.gateway.v2.ClientHello
	30, // 2: liveagent.gateway.v2.WebClientFrame.agent_request:type_name -> liveagent.gateway.v1.GatewayEnvelope
	12, // 3: liveagent.gateway.v2.WebClientFrame.status_get:type_name -> liveagent.gateway.v2.StatusGetRequest
	31, // 4: liveagent.gateway.v2.WebClientFrame.chat_command:type_name -> liveagent.gateway.v1.ChatCommandRequest
	14, // 5: liveagent.gateway.v2.WebClientFrame.chat_prepare:type_name -> liveagent.gateway.v2.ChatPrepareRequest
	15, // 6: liveagent.gateway.v2.WebClientFrame.chat_subscribe:type_name -> liveagent.gateway.v2.ChatSubscribeRequest
	19, // 7: liveagent.gateway.v2.WebClientFrame.chat_unsubscribe:type_name -> liveagent.gateway.v2.ChatUnsubscribeRequest
	20, // 8: liveagent.gateway.v2.WebClientFrame.chat_activities:type_name -> liveagent.gateway.v2.ChatActivitiesRequest
	28, // 9: liveagent.gateway.v2.WebClientFrame.workspace_subscribe:type_name -> liveagent.gateway.v2.WorkspaceSubscribeRequest
	29, // 10: liveagent.gateway.v2.WebClientFrame.workspace_unsubscribe:type_name -> liveagent.gateway.v2.WorkspaceUnsubscribeRequest
	4,  // 11: liveagent.gateway.v2.WebClientFrame.pong:type_name -> liveagent.gateway.v2.PongFrame
	2,  // 12: liveagent.gateway.v2.WebServerFrame.hello:type_name -> liveagent.gateway.v2.ServerHello
	32, // 13: liveagent.gateway.v2.WebServerFrame.agent_response:type_name -> liveagent.gateway.v1.AgentEnvelope
	33, // 14: liveagent.gateway.v2.WebServerFrame.local_error:type_name -> liveagent.gateway.v1.ErrorResponse
	3,  // 15: liveagent.gateway.v2.WebServerFrame.ping:type_name -> liveagent.gateway.v2.PingFrame
	13, // 16: liveagent.gateway.v2.WebServerFrame.status:type_name -> liveagent.gateway.v2.StatusEvent
	18, // 17: liveagent.gateway.v2.WebServerFrame.chat_subscribed:type_name -> liveagent.gateway.v2.ChatSubscribeResult
	23, // 18: liveagent.gateway.v2.WebServerFrame.chat_accepted:type_name -> liveagent.gateway.v2.ChatCommandAccepted
	21, // 19: liveagent.gateway.v2.WebServerFrame.chat_activities:type_name -> liveagent.gateway.v2.ChatActivitiesResult
	22, // 20: liveagent.gateway.v2.WebServerFrame.chat_event:type_name -> liveagent.gateway.v2.ChatStreamEvent
	24, // 21: liveagent.gateway.v2.WebServerFrame.chat_command_update:type_name -> liveagent.gateway.v2.ChatCommandUpdate
	25, // 22: liveagent.gateway.v2.WebServerFrame.chat_subscription_reset:type_name -> liveagent.gateway.v2.ChatSubscriptionReset
	27, // 23: liveagent.gateway.v2.WebServerFrame.chat_activity:type_name -> liveagent.gateway.v2.ChatActivityEvent
	5,  // 24: liveagent.gateway.v2.WebServerFrame.ack:type_name -> liveagent.gateway.v2.AckResult
	26, // 25: liveagent.gateway.v2.WebServerFrame.chat_cancelled:type_name -> liveagent.gateway.v2.ChatCancelResult
	34, // 26: liveagent.gateway.v2.WebServerFrame.history_event:type_name -> liveagent.gateway.v1.HistorySyncEvent
	35, // 27: liveagent.gateway.v2.WebServerFrame.settings_event:type_name -> liveagent.gateway.v1.SettingsSyncEvent
	36, // 28: liveagent.gateway.v2.WebServerFrame.terminal_event:type_name -> liveagent.gateway.v1.TerminalEvent
	37, // 29: liveagent.gateway.v2.WebServerFrame.sftp_event:type_name -> liveagent.gateway.v1.SftpEvent
	38, // 30: liveagent.gateway.v2.WebServerFrame.chat_queue_event:type_name -> liveagent.gateway.v1.ChatQueueEvent
	39, // 31: liveagent.gateway.v2.WebServerFrame.tunnel_state:type_name -> liveagent.gateway.v1.TunnelStateSnapshot
	40, // 32: liveagent.gateway.v2.WebServerFrame.process_state:type_name -> liveagent.gateway.v1.ManagedProcessSnapshot
	41, // 33: liveagent.gateway.v2.WebServerFrame.workspace_activity:type_name -> liveagent.gateway.v1.WorkspaceActivityEvent
	1,  // 34: liveagent.gateway.v2.AgentClientFrame.hello:type_name -> liveagent.gateway.v2.ClientHello
	32, // 35: liveagent.gateway.v2.AgentClientFrame.envelope:type_name -> liveagent.gateway.v1.AgentEnvelope
	2,  // 36: liveagent.gateway.v2.AgentServerFrame.hello:type_name -> liveagent.gateway.v2.ServerHello
	30, // 37: liveagent.gateway.v2.AgentServerFrame.envelope:type_name -> liveagent.gateway.v1.GatewayEnvelope
	1,  // 38: liveagent.gateway.v2.TerminalClientFrame.hello:type_name -> liveagent.gateway.v2.ClientHello
	42, // 39: liveagent.gateway.v2.TerminalClientFrame.frame:type_name -> liveagent.gateway.v1.TerminalStreamFrame
	2,  // 40: liveagent.gateway.v2.TerminalServerFrame.hello:type_name -> liveagent.gateway.v2.ServerHello
	42, // 41: liveagent.gateway.v2.TerminalServerFrame.frame:type_name -> liveagent.gateway.v1.TerminalStreamFrame
	16, // 42: liveagent.gateway.v2.ChatSubscribeResult.activity:type_name -> liveagent.gateway.v2.ChatRunActivity
	17, // 43: liveagent.gateway.v2.ChatSubscribeResult.snapshot:type_name -> liveagent.gateway.v2.ChatRunSnapshot
	16, // 44: liveagent.gateway.v2.ChatActivitiesResult.running_conversations:type_name -> liveagent.gateway.v2.ChatRunActivity
	45, // [45:45] is the sub-list for method output_type
	45, // [45:45] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_proto_v2_gateway_ws_proto_init() }
func file_proto_v2_gateway_ws_proto_init() {
	if File_proto_v2_gateway_ws_proto != nil {
		return
	}
	file_proto_v2_gateway_ws_proto_msgTypes[5].OneofWrappers = []any{
		(*WebClientFrame_Hello)(nil),
		(*WebClientFrame_AgentRequest)(nil),
		(*WebClientFrame_StatusGet)(nil),
		(*WebClientFrame_ChatCommand)(nil),
		(*WebClientFrame_ChatPrepare)(nil),
		(*WebClientFrame_ChatSubscribe)(nil),
		(*WebClientFrame_ChatUnsubscribe)(nil),
		(*WebClientFrame_ChatActivities)(nil),
		(*WebClientFrame_WorkspaceSubscribe)(nil),
		(*WebClientFrame_WorkspaceUnsubscribe)(nil),
		(*WebClientFrame_Pong)(nil),
	}
	file_proto_v2_gateway_ws_proto_msgTypes[6].OneofWrappers = []any{
		(*WebServerFrame_Hello)(nil),
		(*WebServerFrame_AgentResponse)(nil),
		(*WebServerFrame_LocalError)(nil),
		(*WebServerFrame_Ping)(nil),
		(*WebServerFrame_Status)(nil),
		(*WebServerFrame_ChatSubscribed)(nil),
		(*WebServerFrame_ChatAccepted)(nil),
		(*WebServerFrame_ChatActivities)(nil),
		(*WebServerFrame_ChatEvent)(nil),
		(*WebServerFrame_ChatCommandUpdate)(nil),
		(*WebServerFrame_ChatSubscriptionReset)(nil),
		(*WebServerFrame_ChatActivity)(nil),
		(*WebServerFrame_Ack)(nil),
		(*WebServerFrame_ChatCancelled)(nil),
		(*WebServerFrame_HistoryEvent)(nil),
		(*WebServerFrame_SettingsEvent)(nil),
		(*WebServerFrame_TerminalEvent)(nil),
		(*WebServerFrame_SftpEvent)(nil),
		(*WebServerFrame_ChatQueueEvent)(nil),
		(*WebServerFrame_TunnelState)(nil),
		(*WebServerFrame_ProcessState)(nil),
		(*WebServerFrame_WorkspaceActivity)(nil),
	}
	file_proto_v2_gateway_ws_proto_msgTypes[7].OneofWrappers = []any{
		(*AgentClientFrame_Hello)(nil),
		(*AgentClientFrame_Envelope)(nil),
	}
	file_proto_v2_gateway_ws_proto_msgTypes[8].OneofWrappers = []any{
		(*AgentServerFrame_Hello)(nil),
		(*AgentServerFrame_Envelope)(nil),
	}
	file_proto_v2_gateway_ws_proto_msgTypes[9].OneofWrappers = []any{
		(*TerminalClientFrame_Hello)(nil),
		(*TerminalClientFrame_Frame)(nil),
	}
	file_proto_v2_gateway_ws_proto_msgTypes[10].OneofWrappers = []any{
		(*TerminalServerFrame_Hello)(nil),
		(*TerminalServerFrame_Frame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v2_gateway_ws_proto_rawDesc), len(file_proto_v2_gateway_ws_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v2_gateway_ws_proto_goTypes,
		DependencyIndexes: file_proto_v2_gateway_ws_proto_depIdxs,
		EnumInfos:         file_proto_v2_gateway_ws_proto_enumTypes,
		MessageInfos:      file_proto_v2_gateway_ws_proto_msgTypes,
	}.Build()
	File_proto_v2_gateway_ws_proto = out.File
	file_proto_v2_gateway_ws_proto_goTypes = nil
	file_proto_v2_gateway_ws_proto_depIdxs = nil
}
